[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",]

[lint]
exclude_lints = [
  "screaming-snake-case-const",
  "mixed-case-variable",
  "mixed-case-function",
  "asm-keccak256",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
